services:
  app:
    container_name: graphql-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - .:/app
    tty: true
